"""
Core Markdown-to-HTML converter.

Provides ``convert_markdown()`` for the actual parsing pipeline and
``wrap_html()`` for assembling the final self-contained HTML document.
"""

import html as html_mod

import markdown

from . import preprocess
from .templates import DARK_CSS, LIGHT_CSS, MATHJAX_SCRIPT, MERMAID_SCRIPT


def convert_markdown(
    md_text: str,
    theme: str = "light",
    enable_mermaid: bool = True,
    enable_math: bool = True,
    enable_highlight: bool = True,
) -> str:
    """Convert raw Markdown text to an HTML body fragment.

    Args:
        md_text: The Markdown source to convert.
        theme: Pygments colour style hint (``"light"`` or ``"dark"``).
        enable_mermaid: If ``True``, extract and preserve Mermaid blocks
            for client-side rendering.
        enable_math: If ``True``, emit MathJax CDN boilerplate.
        enable_highlight: If ``True``, enable Pygments-based syntax
            highlighting for fenced code blocks.

    Returns:
        An HTML string representing the ``<body>`` content (no ``<html>``
        or ``<head>`` wrapper).
    """
    # --- Pre-processing ---

    md_text = preprocess.fix_list_spacing(md_text)

    mermaid_blocks: dict[str, str] = {}
    if enable_mermaid:
        md_text, mermaid_blocks = preprocess.extract_mermaid_blocks(md_text)

    # --- Markdown extensions ---

    extensions = [
        "markdown.extensions.tables",
        "markdown.extensions.toc",
        "markdown.extensions.sane_lists",
        "markdown.extensions.nl2br",
        "markdown.extensions.abbr",
        "markdown.extensions.attr_list",
        "markdown.extensions.def_list",
        "markdown.extensions.footnotes",
        "markdown.extensions.md_in_html",
        "markdown.extensions.admonition",
        "markdown.extensions.smarty",
        "pymdownx.tasklist",
        "pymdownx.tilde",
        "pymdownx.caret",
        "pymdownx.mark",
        "pymdownx.details",
        "pymdownx.magiclink",
        "pymdownx.betterem",
        "pymdownx.emoji",
    ]

    extension_configs: dict = {
        "pymdownx.tasklist": {
            "custom_checkbox": True,
            "clickable_checkbox": False,
        },
    }

    if enable_highlight:
        extensions.append("pymdownx.highlight")
        extensions.append("pymdownx.superfences")
        extension_configs["pymdownx.highlight"] = {
            "use_pygments": True,
            "noclasses": True,  # inline styles → self-contained output
            "pygments_style": "default" if theme == "light" else "monokai",
            "linenums": False,
            "guess_lang": True,
        }

    md = markdown.Markdown(
        extensions=extensions,
        extension_configs=extension_configs,
        output_format="html5",
        tab_length=2,
    )

    body = md.convert(md_text)

    # --- Post-processing ---

    if mermaid_blocks:
        body = preprocess.restore_mermaid_blocks(body, mermaid_blocks)

    return body


def wrap_html(
    body: str,
    title: str,
    theme: str,
    enable_mermaid: bool,
    enable_math: bool,
    max_width: str = "none",
) -> str:
    """Wrap HTML body content into a self-contained HTML document.

    The output includes embedded CSS (no external stylesheets), optional
    Mermaid and MathJax CDN scripts, and appropriate ``<meta>`` tags.

    Args:
        body: The HTML body content (generated by ``convert_markdown``).
        title: The ``<title>`` and page heading.
        theme: ``"light"`` or ``"dark"``.
        enable_mermaid: Include Mermaid.js CDN boilerplate.
        enable_math: Include MathJax CDN boilerplate.
        max_width: CSS ``max-width`` value for the content area
            (e.g. ``"none"``, ``"960px"``).

    Returns:
        A complete HTML document as a string.
    """
    css = LIGHT_CSS if theme == "light" else DARK_CSS
    css = css.replace("__MAX_WIDTH__", max_width)
    mermaid_theme = "default" if theme == "light" else "dark"

    extra_head = ""
    extra_body = ""

    if enable_mermaid:
        extra_body += MERMAID_SCRIPT.replace("THEME_VAR", mermaid_theme)

    if enable_math:
        extra_head += MATHJAX_SCRIPT

    title_safe = html_mod.escape(title)

    return (
        "<!DOCTYPE html>\n"
        '<html lang="zh-CN">\n'
        "<head>\n"
        '<meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        '<meta name="generator" content="md2html">\n'
        f"<title>{title_safe}</title>\n"
        "<style>\n"
        f"{css}"
        "</style>\n"
        f"{extra_head}"
        "</head>\n"
        "<body>\n"
        f"{body}\n"
        f"{extra_body}"
        "</body>\n"
        "</html>"
    )
